#!/usr/bin/env python3
"""Builds the Part A submission zip:  <entry1>_<entry2>_A.zip

    python3 scripts/package.py <entry1> <entry2>

Contents = exactly what spec A.9 asks for: all sources, the Makefile and the scripts
needed to reproduce the experiments; the README; the report PDF; the plots as PNG
files at the top level; the workload (test files) and the metrics CSVs of every run.
Left out: unit/integration tests (they stay in the git repository), per-run server
logs and config copies, build artefacts, server data dirs, Python caches, internal
notes.
"""
import glob
import os
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TOP_FILES = ["Makefile", "config.json", "README.md", "report_A.pdf"]
TOP_GLOBS = ["fig*.png"]
DIRS = ["src", "scripts", "workload", "results"]


def skip(rel):
    parts = rel.split("/")
    name = parts[-1]
    if "__pycache__" in parts or name.endswith(".pyc"):
        return True
    if any(p.endswith(".data") or p == "_warmup" for p in parts):
        return True  # server storage dirs created by the experiment runs
    if rel.startswith("results/") and not rel.endswith(".csv"):
        return True  # A.9 asks for the metrics CSVs; per-run logs/configs are regenerated by run_all.sh
    if rel == "scripts/package.py":
        return True  # packaging helper, not needed to reproduce the experiments
    return False


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: package.py <entry1> <entry2>")
    entry1, entry2 = sys.argv[1:3]
    out = os.path.join(ROOT, f"{entry1}_{entry2}_A.zip")

    files = []
    for f in TOP_FILES:
        if not os.path.exists(os.path.join(ROOT, f)):
            sys.exit(f"missing required file: {f}")
        files.append(f)
    for g in TOP_GLOBS:
        files += sorted(os.path.basename(p) for p in glob.glob(os.path.join(ROOT, g)))
    for d in DIRS:
        for base, _, names in os.walk(os.path.join(ROOT, d)):
            for n in sorted(names):
                rel = os.path.relpath(os.path.join(base, n), ROOT).replace(os.sep, "/")
                if not skip(rel):
                    files.append(rel)

    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for rel in files:
            z.write(os.path.join(ROOT, rel), rel)
    print(f"{out}: {len(files)} files, {os.path.getsize(out) / 1024:.0f} KB")


if __name__ == "__main__":
    main()
